# Generated by adevtool; do not edit
# For more info, see https://github.com/kdrag0n/adevtool

PRODUCT_SOONG_NAMESPACES += \
    vendor/google_devices/bramble

PRODUCT_PACKAGES += \
    android.hardware.graphics.mapper-impl-qti-display \
    c2_manifest_vendor \
    libadsprpc \
    libfastcvopt \
    libMpeg4SwEncoder \
    libthermalclient \
    pixel-display-default \
    vendor.qti.hardware.display.allocator-service \
    vendor.qti.hardware.display.composer-service

PRODUCT_ENFORCE_RRO_TARGETS := *
